/* ============================================================================
 * AEOS - Abdalla's Educational Operating System
 * File: src/kernel/backtrace.c
 * Description: symbol_lookup and frame-pointer-walking backtrace.
 *              The symbol table itself is generated by scripts/gen-symbols.sh
 *              into a separate translation unit; this file holds only the
 *              code that consumes it.
 * ============================================================================ */

#include <aeos/symbols.h>
#include <aeos/kprintf.h>
#include <aeos/string.h>

extern char _kernel_start;
extern char __stack_top;

/**
 * Binary-search the symbol table for the entry whose address is the largest
 * value less than or equal to `addr`. Writes "<name>+0xN" into `name_buf`,
 * truncated as needed.
 */
void symbol_lookup(uint64_t addr, char *name_buf, uint32_t buf_size)
{
    if (name_buf == NULL || buf_size == 0) {
        return;
    }

    if (aeos_symbols_count == 0 || addr < aeos_symbols[0].addr) {
        snprintf(name_buf, buf_size, "<unknown 0x%x>",
                 (uint32_t)(addr & 0xFFFFFFFFu));
        return;
    }

    uint32_t lo = 0;
    uint32_t hi = aeos_symbols_count;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (aeos_symbols[mid].addr <= addr) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }

    /* lo is the first index whose addr > input, so lo-1 is the answer. */
    uint32_t idx = lo - 1;
    uint64_t offset = addr - aeos_symbols[idx].addr;
    snprintf(name_buf, buf_size, "%s+0x%x",
             aeos_symbols[idx].name, (uint32_t)offset);
}

/**
 * Walk the saved-FP chain starting at `fp`. AArch64 stores [prev_fp, lr] at
 * the address pointed to by x29; the previous frame is at a higher address
 * because the stack grows down. Stop when the chain leaves a sane window or
 * stops growing.
 */
void backtrace(uint64_t fp)
{
    char name[96];
    const uint64_t kernel_start = (uint64_t)&_kernel_start;
    const uint64_t stack_top    = (uint64_t)&__stack_top;

    kprintf("Backtrace:\n");

    if (fp == 0) {
        kprintf("  (frame pointer is null)\n");
        return;
    }

    for (int depth = 0; depth < 16; depth++) {
        /* The FP must point inside the kernel image-and-stack window, with
         * room for an [fp, lr] pair. Anything else is corruption. */
        if (fp < kernel_start || fp + 16 > stack_top) {
            kprintf("  (fp 0x%x out of range)\n", (uint32_t)fp);
            return;
        }

        uint64_t *frame = (uint64_t *)fp;
        uint64_t next_fp = frame[0];
        uint64_t lr = frame[1];

        if (lr == 0) {
            return;
        }

        symbol_lookup(lr, name, sizeof(name));
        kprintf("  #%d  0x%x  %s\n", depth, (uint32_t)(lr & 0xFFFFFFFFu), name);

        if (next_fp == 0) {
            return;
        }
        if (next_fp <= fp) {
            /* The chain must move toward higher addresses; if it doesn't,
             * the saved fp is junk and chasing it would loop or crash. */
            kprintf("  (fp chain does not grow; halting walk)\n");
            return;
        }
        fp = next_fp;
    }

    kprintf("  (truncated at depth 16)\n");
}

/* ============================================================================
 * End of backtrace.c
 * ============================================================================ */
